### ISSUE TITLE
Use multiple datasource.

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#139]
Hi @hatunet , I am looking to  use multiple dataSources for all my addons and want to use spring-data-mybatis with it.

I have read this example of multiple datasource implementation https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7 but it is for JPA.

Do you have a recommendation on how to do it ?

**Comment by easybest** [comment]
spring-data-mybatis supports multiple dataSources

**Comment by kopax** [comment]
Hi @hatunet, could you show me an example of configuration please ? 
My use case is as follow:

I have an 
- application.jar
- core.jar
- module_1.jar (optional)
- module_2.jar (optional)

application.jar will own the configuration of dataSourceCore, dataSourceM1, dataSourceM2.
Each dataSource use it's own schema.

**Comment by kopax** [comment]
# Configuration

I have followed this tutorial to configure two data sources in spring-data : 

https://medium.com/@joeclever/using-multiple-datasources-with-spring-boot-and-spring-data-6430b00c02e7

The tomcat start and the two databases are initialized with flyway with success.

The first DataSource configuration look like this 

```java
@Configuration
@EnableTransactionManagement
@EnableMybatisRepositories(
        value = "com.domain.api.userManagement.repository",
        mapperLocations = {
                "classpath*:/mappers/userManagement/*Mapper.xml",
        }
)
public class UserManagementDbConfig {

    @Value("${api.db.userManagement.version}")
    private String version;

    @Primary
    @Bean(name = "dataSource")
    @ConfigurationProperties(prefix = "api.db.userManagement")
    public DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    @Qualifier("userManagement")
    public PlatformTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean
    public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());
        return sessionFactory;
    }

    @Bean
    public SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory sqlSessionFactory) {
        return new SqlSessionTemplate(sqlSessionFactory);
    }

    @Bean(initMethod = "migrate")
    public Flyway flyway() throws SQLException {
        Flyway flyway = new Flyway();
        flyway.setBaselineOnMigrate(true);
        flyway.setLocations("classpath:db/migration/userManagement");
        flyway.setSqlMigrationPrefix("V");
        flyway.setSqlMigrationSuffix(".sql");
        flyway.setEncoding("UTF-8");
        flyway.setValidateOnMigrate(false);
        flyway.setOutOfOrder(true);
        flyway.setTargetAsString(version);
        flyway.setDataSource(dataSource());
        return flyway;
    }
}
```

And the second DataSource: 

```java
@Configuration
@EnableTransactionManagement
@EnableMybatisRepositories(
        value = "com.domain.api.companyManagement.repository",
        mapperLocations = {
                "classpath*:/mappers/companyManagement/*Mapper.xml",
        }
)
public class CompanyManagementDbConfig {

    @Value("${api.db.companyManagement.version}")
    private String version;

    @Bean(name = "companyManagementDataSource")
    @ConfigurationProperties(prefix = "api.db.companyManagement")
    public DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean
    @Qualifier("companyManagement")
    public PlatformTransactionManager transactionManager(DataSource dataSource) {
        return new DataSourceTransactionManager(dataSource);
    }

    @Bean(name = "companyManagementSqlSessionFactory")
    public SqlSessionFactoryBean sqlSessionFactory() throws Exception {
        final SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());
        return sessionFactory;
    }

    @Bean(name = "companyManagementSqlSessionTemplate")
    public SqlSessionTemplate sqlSessionTemplate(SqlSessionFactory sqlSessionFactory) {
        return new SqlSessionTemplate(sqlSessionFactory);
    }


    @Bean(initMethod = "migrate", name = "companyManagementFlyway")
    public Flyway flyway() throws SQLException {
        Flyway flyway = new Flyway();
        flyway.setBaselineOnMigrate(true);
        flyway.setLocations("classpath:db/migration/companyManagement");
        flyway.setSqlMigrationPrefix("V");
        flyway.setSqlMigrationSuffix(".sql");
        flyway.setEncoding("UTF-8");
        flyway.setValidateOnMigrate(false);
        flyway.setOutOfOrder(true);
        flyway.setTargetAsString(version);
        flyway.setDataSource(dataSource());
        return flyway;
    }
}
```

The service use for the insert:


```java
@Service
public class TestServiceImpl extends AbstractCrudService<TestRepository, Test, Long> implements TestService {

  @Autowired
  public TestServiceImpl(TestRepository repository) {
    super(repository);
  }

  @Override
  @Transactional("companyManagement")
  public void insert(Test user) {
    super.insert(user);
  }

  @Override
  @Transactional("companyManagement")
  public void updateIgnore(Test user) {
    super.updateIgnore(user);
  }
}
```

`application.yml`

```yml
server:
  port: 8080
  session:
    timeout: -1

api:
  db:
    userManagement:
      version: 0.0.17
      url: jdbc:postgresql://localhost:3333/UM?autoReconnect=true&useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=UTF-8
      username: ******
      password: ******
      driver-class-name: org.postgresql.Driver
      minIdle: 0
      maxIdle: 10
      maxActive: 50
      maxWait: 6000
      testOnBorrow: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 1800000
      numTestsPerEvictionRun: 50
      minEvictableIdleTimeMillis: 10
      testWhileIdle: true
    companyManagement:
      version: 0.0.17
      url: jdbc:postgresql://localhost:3334/CM?autoReconnect=true&useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=UTF-8
      username: ******
      password: ******
      driver-class-name: org.postgresql.Driver
      minIdle: 0
      maxIdle: 10
      maxActive: 50
      maxWait: 6000
      testOnBorrow: true
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 1800000
      numTestsPerEvictionRun: 50
      minEvictableIdleTimeMillis: 10
      testWhileIdle: true
```

# Result

```
Fri Nov 03 17:18:46 ICT 2017
There was an unexpected error (type=Internal Server Error, status=500).
### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: relation "cm_test" does not exist Position: 13 ### The error may involve com.domain.api.companyManagement.domain.Test._insert-Inline ### The error occurred while setting parameters ### SQL: insert into "cm_test"("name") values(?) ### Cause: org.postgresql.util.PSQLException: ERROR: relation "cm_test" does not exist Position: 13 ; bad SQL grammar []; nested exception is org.postgresql.util.PSQLException: ERROR: relation "cm_test" does not exist Position: 13
```

This repository should be trying to insert in the 2nd datasource but it try to use the 1st (main) data source.

`@Transactional` is ignored

# Reproduction

url: https://github.com/kopax/spring-data-mybatis-test
You need to start the two database using `docker-compose up -d` or manually without docker.


How did you manage to use multiple DataSource ?
