### ISSUE TITLE
@RepositoryRestResource vs @Repository

### ISSUE THREAD

**Issue by kopax** [easybest/spring-data-mybatis#39]
In your updated readme you don't use anymore @EnableMybatisRepository.

I can't remove it because there is two parameter to pass to this annotation : `value`, `mapperLocations`.

Only one of these two can be configured by using application.properties, so I have to mix it 

```yml
spring:
  data:
    mybatis:
      mapper-Locations: classpath*:/mappers/*Mapper.xml
```

```java
@EnableMybatisRepositories(
	value = "com.repository"
//	mapperLocations = "classpath*:/mappers/*Mapper.xml"
)
```

Would be nice to move the value somewhere else, that would be useful for testing purpose, so we don't have to copy the configuration.

Also you have replaced the `@Repository` annotation that expose to spring-data-rest, by this one `@RepositoryRestResource`.

It work fine but I would like to know the difference between those two.
